---
resource_types:
  - name: custom-docker-image-resource
    type: docker-image
    privileged: true
    source:
      repository: jaedle/custom-docker-image-resource
      tag: latest

resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:jaedle/caddy-webdav.git
      private_key: ((ci-key))

  - name: caddy-webdav-image
    type: custom-docker-image-resource
    source:
      repository: jaedle/caddy-webdav
      username: ((docker-username))
      password: ((docker-password))
      remote_docker:
        host: ((remote-docker-host))
        ssh_key: ((remote-docker-ssh-key))

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true
      - put: caddy-webdav-image
        params:
          build: source-code/
